### ISSUE TITLE
virustotal.com reports trojan?

### ISSUE THREAD

**Issue by Nemesis77swe** [cubiclesoft/messagebox-windows#3]
I'm curious, is this a fake positive?

[Total virus scan](https://www.virustotal.com/gui/file/d42c8e56b386c2cdbf0b9fb6668ada25cf52aa1d4f98daccfbea2126d88d963d/detection)

**Comment by cubiclesoft** [comment]
When using VirusTotal, you should upload individual binaries rather than entire ZIP files.  Otherwise you won't know what file was triggered on.  It could have been the `build.bat` file for all you could tell.  But it was the EXEs in this case:

https://www.virustotal.com/gui/file/6a4db98e46d6ce7ad55a4cd726cb14d369fbba0202dc0a504a01b059a8f0d913/detection

https://www.virustotal.com/gui/file/e0f1a062323edeeab5b8da5867e0d809340dae160dfc161d2511a4ac32a608f4/detection

Only very minor anti-malware players are showing up.  Not sure what they don't like about the binaries but 3 of the 4 all claim to use "Artificial Intelligence" to detect malware and use "the cloud" to evaluate whether or not to run a piece of software.  If I were to guess what that combination means in this context:  "We've convinced some people to purchase our software and install it on their corporate systems.  When someone uploads a random, unsigned binary or two to VirusTotal that few people have run in the corporate environments then we're going to assume that it is a virus.  We're gonna block that software until at least one person at those companies who bought our anti-malware software says it is actually okay."  I could write that trash in my sleep.  Nothing intelligent about it.  And the 4th product, MaxSecure, apparently frequently flags false positives for all kinds of software (i.e. it's not very good AV software and can be ignored).

So, in short, a number of false positives.  You can always [build it yourself with Visual Studio](https://visualstudio.microsoft.com/downloads/) if you are concerned.  The source code and build batch file are, after all, part of the repository.  I build this project with Visual Studio 2013 Community Edition, which produces slightly smaller statically linked EXEs than newer VS releases and the resulting binaries also run on most versions of Windows (theoretically back to Windows XP).  But it should build just fine with more recent Visual Studio releases.

Your own generated binaries may also trip up those same malware vendors.  Or not.  Or different ones.  Because each time a program is compiled, the binary changes slightly (e.g. the date and time the program was compiled and linked) and those subtle differences are enough to trip up or not trip up AV software even if nothing's changed in the source code itself.

For comparison, I recently released a series of major updates to the [CreateProcess tool](https://github.com/cubiclesoft/createprocess-windows), which I would expect to trip up a whole lot more AV software:

https://www.virustotal.com/gui/file/623d5751115f1f4cb08b803e60cb35fc8ad92e50eaea4c36c955f1e0e6867fd3/detection

MaxSecure is notably missing.  So whatever _it_ didn't like about MessageBox is somehow missing from or okay with in CreateProcess.  Both MessageBox and CreateProcess were built quite recently with the same version of Visual Studio.

The most recent modifications to the CreateProcess tool allow running software as NT AUTHORITY\SYSTEM via standard elevation and calls two undocumented Windows NT kernel APIs as well as dragging in the Windows TCP/IP socket DLLs from before.  So I'm not surprised to see a couple of major AV vendors pick up on all of that as being possibly problematic.  But those paths in the code require an attempt to execute those paths.  So, again, false positives.  And the source code is available for perusal and self-compilation.  I'm actually surprised at how few it actually trips up.  Was expecting to see more.  There should be far more false positives over CreateProcess given what it does today.  But what it does is harmless even if it is a tad unusual.

If I spent $700/year and code-signed the executables with an EV code-signing cert, all of the false positives might go away.  For example, I know for sure that Windows Defender doesn't scan code-signed executables as rigorously (and possibly not at all!) but I think code signing just to get past AV software is ridiculous.  Not everyone can afford the expensive certs either, especially small ISVs.  AV vendors rely on fear to keep themselves in business.  And EV code-signing certs are insanely overpriced - especially renewals...the Microsoft-approved vendors that sell them charge the exact same amount each year but the amount of work involved in a renewal is literally rubber-stamping a cert:  "Huh.  I guess they are still in business.  We haven't bled them dry yet.  Looks good.  Thanks for the $$$$$$$.  I clicked a couple of buttons on my end and here's your certificate.  See you next year!"  Vultures.

Anti-malware software is exceptionally dumb and triggers false positives all over the place.  For example, put this into a file with a .php extension and save it:

```php
<?php
  system("php.exe runsomething.php");
```

According to Microsoft Windows Defender, that is apparently malware and it will delete the file off disk to keep you "safe."  But this:

```php
<?php
  // I'm just a nice comment.
  system("php.exe runsomething.php");
```

Is apparently not malware.  Windows Defender will declare the first file to be a virus and delete it off the system, which is frustrating because the person just wrote it and saved it to disk using their text editor and needs to test something.  The second file is totally fine though, because somehow a little comment at the top of a file fixes the problem but also magically stops actual malware that might follow a similar pattern.  Thanks Microsoft.

Another example of anti-malware software being exceptionally dumb, PuTTY (a very popular SSH client) was recently declared to be malware by multiple commercial AV products because some malware author bundled a version of PuTTY with their PDF malware.  So everything bundled in the PDF malware got swept up as being malware.  Just another dumb example of false positives triggering deletions of perfectly fine software on a system.  I was lagging behind on the latest version of PuTTY, so updating to the latest version seemed to not trigger detection.  I also found the version I was using from the original author's site and attempting to put it on my system triggered each time.  But, still, it was stupid that a widely used, well-known, harmless software product got declared malware because a malware author bundled that software with their malware.

As I said, if you are concerned, compile it for yourself.  I mean, this is the Internet.  Trusting a total stranger not to mess up your system with an executable from an unknown GitHub repo is a valid concern.  So, sure, use caution with random binaries and build from source.  The binaries are a convenience.

**Comment by Nemesis77swe** [comment]
Thanks for the long answer, I didn't mean to offend you, I was just curious.
I should rather thank you for doing these "small" programs that nobody else are doing.
I checked the other program, and I might be interested in that to..

it was very interesting to learn little how "stupid" some "anti"virus are..
i also did a quick read of your code on my phone earlier, and I didn't see any malicious..

**Comment by cubiclesoft** [comment]
Oh you did not offend me.  I wrote that extensive response to give me something I can link to in the future if someone else points it out as well.  Because that kind of thing is inevitable.

I just have to remember that I wrote it.  😊

**Comment by Nemesis77swe** [comment]
did just so, I compiled it, and the same two scanners complained about my file to...

https://www.virustotal.com/gui/file/79e437456b8715a5cfe2e5a12ad6ecbb96269aabeb5d962d750c6761a9945259/detection

**Comment by cubiclesoft** [comment]
Awesome.

Actually it looks like a different scanner came up on yours (Jiangmin vs. MaxSecure).

**Comment by Nemesis77swe** [comment]
yeah, (I did use the 2019 version) and since the code is clean, and I'm using visual basic to compile it, it must be Microsoft that's adding something "malicious" 😆

btw, any command to get it to release the batch file without awaiting an answer on the message?

**Comment by cubiclesoft** [comment]
Use `messagebox-win.exe`.  That will start the process in the background without waiting.
